In [2]:
import pandas as pd
import numpy as np
from datetime import date
import sqlite3
import requests
from pprint import pprint
import csv
import json

In [3]:
la_county_zip_boundaries = requests.get("https://data.lacounty.gov/resource/dwvh-6kjy.json").json()
la_county_zip_boundaries[0]['zipcode']

la_county_zip_list = []
for zip in enumerate(d['zipcode'] for d in la_county_zip_boundaries):
    la_county_zip_list.append(zip)

la_county_zip_list_df = pd.DataFrame(la_county_zip_list).drop(columns=[0]).rename(columns={1:'zip'})
la_county_zip_list_df['zip'] = la_county_zip_list_df['zip'].apply(pd.to_numeric)
la_county_zip_list_df = la_county_zip_list_df.set_index('zip')
la_county_zip_list_df.head()             # 311 zips in la_zip_list

Empty DataFrame
Columns: []
Index: [90001, 90002, 90003, 90004, 90005]

In [4]:
# Read la_city_zips.csv into dataframe
la_city_zip_list_df = pd.read_csv("la_city_zips.csv")
la_city_zip_list_df['zip'] = la_city_zip_list_df['zip'].apply(pd.to_numeric)
la_city_zip_list_df = la_city_zip_list_df.set_index('zip')
la_city_zip_list_df.head()

Empty DataFrame
Columns: []
Index: [90001, 90002, 90003, 90004, 90005]

In [5]:
zip_boundaries = requests.get("http://s3-us-west-2.amazonaws.com/boundaries.latimes.com/archive/1.0/boundary-set/zip-code-tabulation-areas-2012.geojson").json()
zips = zip_boundaries['features']

zip_list = []
for zip in enumerate(d['properties']['name'] for d in zips):
    zip_list.append(zip)
    
zip_list_df = pd.DataFrame(zip_list).drop(columns=[0]).rename(columns={1:'zip'})
zip_list_df['zip'] = zip_list_df['zip'].apply(pd.to_numeric)
zip_list_df = zip_list_df.set_index('zip')
zip_list_df.head()

Empty DataFrame
Columns: []
Index: [90001, 90002, 90003, 90004, 90005]

In [6]:
zip_combined_stats_df = pd.read_csv("Combined_Hosp_Drug_Util_v3.csv")
zip_combined_stats_df = zip_combined_stats_df.set_index(['zip'])
scal_zip_stats_df = zip_combined_stats_df.merge(zip_list_df, on='zip', how='inner')
la_zip_stats_df = scal_zip_stats_df.merge(la_city_zip_list_df, on='zip', how='inner')

# Create list of zips for reference in the map_logic.js file
la_zips = json.dumps(list(map(str, la_zip_stats_df.index.values.tolist())))
la_zips_for_js = f"la_zips={la_zips}"
with open("../static/js/la_zips.js", "w") as output:
    output.write(str(la_zips_for_js))

In [7]:
la_zip_stats_df.dtypes

latitude                                   float64
longitude                                  float64
county                                      object
state                                       object
year                                         int64
total_pop                                    int64
male_pop                                     int64
pct_male                                   float64
female_pop                                   int64
pct_female                                 float64
total_employable_pop                         int64
full_time_employed_pop                       int64
pct_full_time_employed_pop                 float64
total_households                             int64
household_median_income                      int64
insurable_pop                                int64
insured_pop                                  int64
pct_insured                                float64
uninsured_pop                                int64
adi_state_rank                             float64
adi_natl_rank                              float64
ca_doi_underserved_flag                     object
tapestry_seg_nr                              int64
tapestry_seg_code                           object
tapestry_seg_name                           object
lifemode_code                                int64
lifemode_group                              object
as_only                                      int64
ed_only                                      int64
inpatient                                    int64
                                            ...
sui                                          int64
total_deaths                                 int64
total_deaths_per_1000                      float64
alzheimers_deaths_per_1000                 float64
cancer_deaths_per_1000                     float64
clrd_deaths_per_1000                       float64
diabetes_deaths_per_1000                   float64
heart_disease_deaths_per_1000              float64
hypertension_deaths_per_1000               float64
accidental_deaths_per_1000                 float64
chronic_liver_disease_deaths_per_1000      float64
nephrotic_diseases_deaths_per_1000         float64
other_deaths_per_1000                      float64
pneumonia_and_influenza_deaths_per_1000    float64
stroke_deaths_per_1000                     float64
suicide_deaths_per_1000                    float64
c2                                           int64
c3                                           int64
c4                                           int64
c2_c4                                        int64
as_per_1000                                float64
ed_per_1000                                float64
ip_per_1000                                float64
ip_via_ed_per_1000                         float64
c2_per_1000                                float64
c3_per_1000                                float64
c4_per_1000                                float64
c2_c4_per_1000                             float64
opioid_rx_per_1000                         float64
pop_w_opioid_rx_per_1000                   float64
Length: 76, dtype: object

In [8]:
# Create sqlalchemy engine
from sqlalchemy import create_engine

conn = sqlite3.connect("../db/la_crime.db")
c = conn.cursor()
c.execute('''DROP TABLE IF EXISTS la_zip_stats;''')
c.execute('''CREATE TABLE la_zip_stats
            (zip VARCHAR(5) PRIMARY KEY ASC,
             latitude FLOAT,
             longitude FLOAT,
             county VARCHAR(64),
             state VARCHAR(64),
             year INTEGER,
             total_pop INTEGER,
             male_pop INTEGER,
             pct_male FLOAT,
             female_pop INTEGER,
             pct_female FLOAT,
             total_employable_pop INTEGER,
             full_time_employed_pop INTEGER,
             pct_full_time_employed_pop FLOAT,
             total_households INTEGER,
             household_median_income INTEGER,
             insurable_pop INTEGER,
             insured_pop INTEGER,
             pct_insured FLOAT,
             uninsured_pop INTEGER,
             adi_state_rank FLOAT,
             adi_natl_rank FLOAT,
             ca_doi_underserved_flag VARCHAR(1),
             tapestry_seg_nr INTEGER,
             tapestry_seg_code VARCHAR(4),
             tapestry_seg_name VARCHAR(64),
             lifemode_code INTEGER,
             lifemode_group VARCHAR(64),
             as_only INTEGER,
             ed_only INTEGER,
             inpatient INTEGER,
             inpatient_from_ed INTEGER,
             opioid_rx_count INTEGER,
             pop_w_opioid_rx INTEGER,
             tot_opioid_rx_fills INTEGER,
             alz INTEGER,
             can INTEGER,
             cld INTEGER,
             dia INTEGER,
             htd INTEGER,
             hyp INTEGER,
             inj INTEGER,
             liv INTEGER,
             nep INTEGER,
             oth INTEGER,
             pnf INTEGER,
             stk INTEGER,
             sui INTEGER,
             total_deaths INTEGER,
             total_deaths_per_1000 INTEGER,
             alzheimers_deaths_per_1000 FLOAT,
             cancer_deaths_per_1000 FLOAT,
             clrd_deaths_per_1000 FLOAT,
             diabetes_deaths_per_1000 FLOAT,
             heart_disease_deaths_per_1000 FLOAT,
             hypertension_deaths_per_1000 FLOAT,
             accidental_deaths_per_1000 FLOAT,
             chronic_liver_disease_deaths_per_1000 FLOAT,
             nephrotic_diseases_deaths_per_1000 FLOAT,
             other_deaths_per_1000 FLOAT,
             pneumonia_and_influenza_deaths_per_1000 FLOAT,
             stroke_deaths_per_1000 FLOAT,
             suicide_deaths_per_1000 FLOAT,
             c2 INTEGER,
             c3 INTEGER,
             c4 INTEGER,
             c2_c4 INTEGER,
             as_per_1000 FLOAT,
             ed_per_1000 FLOAT,
             ip_per_1000 FLOAT,
             ip_via_ed_per_1000 FLOAT,
             c2_per_1000 FLOAT,
             c3_per_1000 FLOAT,
             c4_per_1000 FLOAT,
             c2_c4_per_1000 FLOAT,
             opioid_rx_per_1000 FLOAT,
             pop_w_opioid_rx_per_1000 FLOAT)
             ''')

conn.commit()
conn.close()

In [9]:
# Create original table
engine = create_engine('sqlite:///../db/la_crime.db')
la_zip_stats_df.to_sql('la_zip_stats', engine, if_exists='append', index=True, )